# Shell commands
START_RABBIT_CMD = "sudo ERL_EPMD_PORT={EPMD_PORT} RABBITMQ_NODE_PORT={PORT} RABBITMQ_NODENAME={NODENAME} RABBITMQ_DIST_PORT={DIST_PORT} rabbitmq-server"
START_RABBIT_APP_CMD = "sudo ERL_EPMD_PORT={EPMD_PORT} rabbitmqctl -n {NODENAME} start_app"
ADD_RABBIT_USER = "sudo ERL_EPMD_PORT={EPMD_PORT} rabbitmqctl -n {NODENAME} add_user {USERNAME} {PASS}"
SET_USER_TAGS = "sudo ERL_EPMD_PORT={EPMD_PORT} rabbitmqctl -n {NODENAME} set_user_tags {USERNAME} administrator"
STOP_RABBIT_APP = "sudo ERL_EPMD_PORT={EPMD_PORT} rabbitmqctl -n {NODENAME} stop_app"
JOIN_CLUSTER_CMD = "sudo ERL_EPMD_PORT={EPMD_PORT} rabbitmqctl -n {NODENAME} join_cluster {MASTER_NODE}"

# Port indices
RABBIT_PORT_INDEX = 1
RABBIT_DIST_PORT_INDEX = 2
EPMD_PORT_INDEX = 3
WS_PORT_INDEX = 0